# Generated by Django 2.2.5 on 2019-10-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REprop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_number',
            field=models.IntegerField(max_length=50),
        ),
    ]
